#Eliminamos la version ya que esta obsoleto. Con la nueva convencion no se utiliza.

services:

  app:
    build:
      context: .
    container_name: kata_auth_app
    environment:
        - JWT_SECRET_KEY=supersecretkey
        - DB_NAME=auth_db
        - DB_USER=postgres
        - DB_PASSWORD=postgres_password
        - DB_HOST=db
        - DB_PORT=5432

    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    container_name: kata_auth_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: auth_db

    ports:
      - 6001:5432 #Se cambia al 6001 para evitar conflictos con postgres Local

    volumes: #Permite que los datos de PostgreSQL persistan aunque el contenedor se elimine.
      - kata_auth_postgres_data:/var/lib/postgresql/data


volumes:
  kata_auth_postgres_data: