version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_auth_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db

    ports:
      - 6000:5432 #Se cambia al 6000 para evitar conflictos con postgres Local

    volumes: #Permite que los datos de PostgreSQL persistan aunque el contenedor se elimine.
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: