version: '3.8'

services:
  db:
    image: postgres
    container_name: kata_auth_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: auth_db

    ports:
      - 6001:5432 #Se cambia al 6000 para evitar conflictos con postgres Local

    volumes: #Permite que los datos de PostgreSQL persistan aunque el contenedor se elimine.
      - kata_auth_postgres_data:/var/lib/postgresql/data


volumes:
  kata_auth_postgres_data: